### ISSUE TITLE
Run time failure

### ISSUE THREAD

**Issue by webmutation** [Toxicable/module-loading#2]
zone.js:2933 GET http://localhost:4200/assets/plugins/myplugin-cli/plugin-metadata.json 404 (Not Found)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ long-stack-trace-zone.js:117
ZoneDelegate.scheduleTask @ zone.js:405
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ xhr_backend.ts:156
Observable._trySubscribe @ Rx.js:1237
Observable.subscribe @ Rx.js:1225
MapOperator.call @ Rx.js:6167
Observable.subscribe @ Rx.js:1222
MapOperator.call @ Rx.js:6167
Observable.subscribe @ Rx.js:1222
webpackJsonp.43.DynamicComponentLoader.ngOnInit @ dynamic-plugin-loader.component.ts:51
checkAndUpdateDirectiveInline @ provider.ts:276
checkAndUpdateNodeInline @ view.ts:519
checkAndUpdateNode @ view.ts:462
debugCheckAndUpdateNode @ services.ts:389
debugCheckDirectivesFn @ services.ts:476
(anonymous) @ AppComponent.html:2
debugUpdateDirectives @ services.ts:455
checkAndUpdateView @ view.ts:375
callViewAction @ view.ts:770
execComponentViewsAction @ view.ts:703
checkAndUpdateView @ view.ts:432
callWithDebugContext @ services.ts:829
debugCheckAndUpdateView @ services.ts:397
ViewRef_.detectChanges @ refs.ts:441
(anonymous) @ application_ref.ts:713
ApplicationRef_.tick @ application_ref.ts:713
ApplicationRef_._loadComponent @ application_ref.ts:560
ApplicationRef_.bootstrap @ application_ref.ts:550
(anonymous) @ application_ref.ts:415
PlatformRef_._moduleDoBootstrap @ application_ref.ts:415
(anonymous) @ application_ref.ts:371
ZoneDelegate.invoke @ zone.js:392
onInvoke @ ng_zone.ts:296
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ ng_zone.ts:288
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
PlatformRef_._bootstrapModuleWithZone @ application_ref.ts:333
PlatformRef_.bootstrapModule @ application_ref.ts:371
39 @ main.ts:11
__webpack_require__ @ bootstrap 51c4dfb7eec49f792497:52
100 @ main.bundle.js:7
__webpack_require__ @ bootstrap 51c4dfb7eec49f792497:52
webpackJsonpCallback @ bootstrap 51c4dfb7eec49f792497:23
(anonymous) @ main.bundle.js:1
errors.ts:42 ERROR Response {_body: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta char…n-cli/plugin-metadata.json</pre>↵</body>↵</html>↵", status: 404, ok: false, statusText: "Not Found", headers: Headers, …}
defaultErrorLogger @ errors.ts:42
ErrorHandler.handleError @ error_handler.ts:69
next @ application_ref.ts:371
schedulerFn @ event_emitter.ts:99
SafeSubscriber.__tryOrUnsub @ Rx.js:983
SafeSubscriber.next @ Rx.js:930
Subscriber._next @ Rx.js:871
Subscriber.next @ Rx.js:835
Subject.next @ Rx.js:1463
EventEmitter.emit @ event_emitter.ts:80
(anonymous) @ ng_zone.ts:319
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ ng_zone.ts:247
onHandleError @ ng_zone.ts:319
ZoneDelegate.handleError @ zone.js:396
Zone.runTask @ zone.js:195
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ long-stack-trace-zone.js:117
ZoneDelegate.scheduleTask @ zone.js:405
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ xhr_backend.ts:156
Observable._trySubscribe @ Rx.js:1237
Observable.subscribe @ Rx.js:1225
MapOperator.call @ Rx.js:6167
Observable.subscribe @ Rx.js:1222
MapOperator.call @ Rx.js:6167
Observable.subscribe @ Rx.js:1222
webpackJsonp.43.DynamicComponentLoader.ngOnInit @ dynamic-plugin-loader.component.ts:51
checkAndUpdateDirectiveInline @ provider.ts:276
checkAndUpdateNodeInline @ view.ts:519
checkAndUpdateNode @ view.ts:462
debugCheckAndUpdateNode @ services.ts:389
debugCheckDirectivesFn @ services.ts:476
(anonymous) @ AppComponent.html:2
debugUpdateDirectives @ services.ts:455
checkAndUpdateView @ view.ts:375
callViewAction @ view.ts:770
execComponentViewsAction @ view.ts:703
checkAndUpdateView @ view.ts:432
callWithDebugContext @ services.ts:829
debugCheckAndUpdateView @ services.ts:397
ViewRef_.detectChanges @ refs.ts:441
(anonymous) @ application_ref.ts:713
ApplicationRef_.tick @ application_ref.ts:713
ApplicationRef_._loadComponent @ application_ref.ts:560
ApplicationRef_.bootstrap @ application_ref.ts:550
(anonymous) @ application_ref.ts:415
PlatformRef_._moduleDoBootstrap @ application_ref.ts:415
(anonymous) @ application_ref.ts:371
ZoneDelegate.invoke @ zone.js:392
onInvoke @ ng_zone.ts:296
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ ng_zone.ts:288
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
PlatformRef_._bootstrapModuleWithZone @ application_ref.ts:333
PlatformRef_.bootstrapModule @ application_ref.ts:371
39 @ main.ts:11
__webpack_require__ @ bootstrap 51c4dfb7eec49f792497:52
100 @ main.bundle.js:7
__webpack_require__ @ bootstrap 51c4dfb7eec49f792497:52
webpackJsonpCallback @ bootstrap 51c4dfb7eec49f792497:23
(anonymous) @ main.bundle.js:1

**Comment by Toxicable** [comment]
I would suggest taking a look at how you can dynamic content via this method here
https://www.youtube.com/watch?v=__H65AsA_bE&feature=youtu.be&t=2h14m13s
demo here
https://stackblitz.com/edit/angular-dynamic-content-viewer
