### ISSUE TITLE
Not loading module on angular 4.4.6 and/or 5.0.1

### ISSUE THREAD

**Issue by xino1010** [Toxicable/module-loading#3]
I created an umd library using rollup and angular 5.
I modified your code to load my own library and Everythings works, but integrating your code in my project I have a troubble on this part.

`
// ANGULAR
import { Component, ComponentFactory, ComponentFactoryResolver, Injector, Input, NgModuleFactory, NgModuleRef, OnInit, ViewContainerRef, ViewChild } from '@angular/core';

// CLASSES
import { MetadataModule } from '../../classes/metadata-module';
import { ModuleData } from '../../classes/module-data';

// SERVICES
import { ModuleService } from '../../services/module.service';

@Component({
  selector: 'dynamic-component-loader',
  template: ''
})
export class DynamicLoaderComponent implements OnInit {

  @Input('moduleData') moduleData: ModuleData;
  private factorySuffix: string = 'NgFactory';
  private pluginEntryPointToken: string = 'PLUGIN_ENTRY_POINT';

  constructor(
    private injector: Injector,
    private _resolver: ComponentFactoryResolver,
    private moduleService: ModuleService,
    private viewRef: ViewContainerRef,
  ) { }

  ngOnInit() {
    console.log('DynamicLoaderComponent ngOnInit');
    console.log(this.moduleData);

    this.moduleService.loadMetadataFile(this.moduleData.metadata)
      .subscribe((metadataModule: MetadataModule) => {
        console.log(metadataModule);
        const script: HTMLScriptElement = document.createElement('script');
        script.src = this.moduleData.library;
        script.onload = () => {
          console.log('script loaded');
          const moduleFactory: NgModuleFactory<any> = window[metadataModule.name][metadataModule.moduleName + this.factorySuffix];
          const moduleRef: NgModuleRef<any> = moduleFactory.create(this.injector);
          const compType = moduleRef.injector.get(this.pluginEntryPointToken);
          const compFactory: ComponentFactory<any> = moduleRef.componentFactoryResolver.resolveComponentFactory(compType);
          this.viewRef.createComponent(compFactory);
        };
        document.head.appendChild(script);
      });

  }

}

`

ERROR Error: StaticInjectorError[RendererFactory2]: 
  StaticInjectorError[RendererFactory2]: 
    NullInjectorError: No provider for RendererFactory2!
    at _NullInjector.webpackJsonp../node_modules/@angular/core/esm5/core.js._NullInjector.get

this is my repo: https://github.com/xino1010/angular-external-modules

**Comment by xino1010** [comment]
If you prefer, I could create a repository for you to look at it

**Comment by xino1010** [comment]
**library-metadata.json**

`{
  "moduleName": "ModuleAModule",
  "name": "module-a"
}
`

**module-a.umd.js**

(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core'), require('@angular/common')) :
	typeof define === 'function' && define.amd ? define(['exports', '@angular/core', '@angular/common'], factory) :
	(factory((global['module-a'] = {}),global.ng.core,global.ng.common));
}(this, (function (exports,i0,i3) { 'use strict';

var Component1Component = (function () {
    function Component1Component() {
    }
    Component1Component.prototype.ngOnInit = function () {
    };
    Component1Component.decorators = [
        { type: i0.Component, args: [{
                    selector: 'app-component1',
                    template: "\n    <p>\n      component1 works!\n    </p>\n  ",
                    styles: ["\n\n  "],
                    encapsulation: i0.ViewEncapsulation.None
                },] },
    ];
    /** @nocollapse */
    Component1Component.ctorParameters = function () { return []; };
    return Component1Component;
}());

var ɵ0 = Component1Component;
var ModuleAModule = (function () {
    function ModuleAModule() {
    }
    ModuleAModule.decorators = [
        { type: i0.NgModule, args: [{
                    entryComponents: [
                        Component1Component,
                    ],
                    declarations: [
                        Component1Component,
                    ],
                    imports: [
                        i3.CommonModule
                    ],
                    providers: [
                        //provide a token for the base to know what component to render
                        {
                            provide: 'PLUGIN_ENTRY_POINT',
                            useValue: ɵ0
                        },
                    ]
                },] },
    ];
    /** @nocollapse */
    ModuleAModule.ctorParameters = function () { return []; };
    return ModuleAModule;
}());

/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var styles_Component1Component = ["\n\n  "];
var RenderType_Component1Component = i0.ɵcrt({ encapsulation: 2, styles: styles_Component1Component, data: {} });
function View_Component1Component_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵted(-1, null, ["\n    "])), (_l()(), i0.ɵeld(1, 0, null, null, 1, "p", [], null, null, null, null, null)), (_l()(), i0.ɵted(-1, null, ["\n      component1 works!\n    "])), (_l()(), i0.ɵted(-1, null, ["\n  "]))], null, null); }
function View_Component1Component_Host_0(_l) { return i0.ɵvid(0, [(_l()(), i0.ɵeld(0, 0, null, null, 1, "app-component1", [], null, null, null, View_Component1Component_0, RenderType_Component1Component)), i0.ɵdid(1, 114688, null, 0, Component1Component, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
var Component1ComponentNgFactory = i0.ɵccf("app-component1", Component1Component, View_Component1Component_Host_0, {}, {}, []);

/**
* @fileoverview This file is generated by the Angular template compiler.
* Do not edit.
* @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
* tslint:disable
*/ 
var ModuleAModuleNgFactory = i0.ɵcmf(ModuleAModule, [], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [Component1ComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(4608, i3.NgLocalization, i3.NgLocaleLocalization, [i0.LOCALE_ID, [2, i3.ɵa]]), i0.ɵmpd(512, i3.CommonModule, i3.CommonModule, []), i0.ɵmpd(512, ModuleAModule, ModuleAModule, []), i0.ɵmpd(256, "PLUGIN_ENTRY_POINT", ɵ0, [])]); });

exports.ModuleAModuleNgFactory = ModuleAModuleNgFactory;

Object.defineProperty(exports, '__esModule', { value: true });

})));

**Comment by Toxicable** [comment]
I would suggest taking a look at how you can dynamic content via this method here
https://www.youtube.com/watch?v=__H65AsA_bE&feature=youtu.be&t=2h14m13s
demo here
https://stackblitz.com/edit/angular-dynamic-content-viewer
